import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["900", "700", "500"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>{children}</body>
    </html>
  );
}

// Miane isme yahi sikha hai like ki inter font jo hoga usme mai apne hisab s weight add kar sakta hau okkh!> \
// iske hisab s heading and paraGraph dono same ayega okkh!...
// inter font mao

// But aisa isme nahi hota like in geist etc font m iske alg hota hai and inter mai dono ka size same hi hota hai and isko mai wigt ke hisab s change kar skata hu in inter font
// that's why inter font are good bcz isme mai dono ek jaisa rkh sakta hu okkh!...
