import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full `}
      >
        {children}
      </body>
    </html>
  );
}

// Dekh bhai mughe agar sare conatiner like sare route's p chize chnage karni hongi na agar to mai is body k andar chize change karunag okkh!..
// body k andar chnage karte hi sare routes p chize chnage ho jayengi okkh!>.
//
